### ISSUE TITLE
Really Data-Free?

### ISSUE THREAD

**Issue by TongKangheng** [zhoumingyi/DaST#12]
I think the most inspiring idea in your paper is that you can train a surrogate model without original dataset. However, today I read your code and find that when you train G model and D model, you will test the classification accuracy and attack success rate on target dataset(for example, cifar10) every epoch, and you only save the model when those are increasing! In such a scene, are you still qualified to claim that your method is data-free?

**Comment by zhoumingyi** [comment]
In the code, we just use the real data for evaluations, which is not an essential step for training an substitute model. In the real-world setting, you can set a max_epoch_num parameter to stop the training. In practice, the performance of the substitute model may be stable after 100 or 200 epochs. We use the evaluation because we need to know whether the algorithm converges (sometimes the training will collapse) and show the best performance of our method on public datasets.
